/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from 'react-native';

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    screen: '#F6F8FC',
    card: '#FFFFFF',
    panel: '#FFFFFF',
    border: '#E4EAF5',
    muted: '#6B7894',
    primary: '#007AFB',
    soft: '#EEF5FF',
    surfaceMuted: '#F1F5F9',
    inputBackground: '#F8FAFC',
    tabBar: '#FFFFFF',
    tabInactive: '#6B7280',
    badgeBackground: '#F1F7FF',
    separator: '#EEF4FF',
    feedBackground: '#F0F2F5',
    incomingBubble: '#F6F7FB',
    incomingText: '#11181C',
    outgoingBubble: '#007AFB',
    outgoingText: '#FFFFFF',
    danger: '#F87171',
    success: '#12B76A',
    infoSurface: '#EAF3FF',
    infoBorder: '#CFE0FF',
    warningSurface: '#FFF7ED',
    warningBorder: '#FED7AA',
    warningText: '#C2410C',
    dangerSurface: '#FEF2F2',
    dangerBorder: '#FECACA',
    successSurface: '#ECFDF3',
    successBorder: '#ABEFC6',
    modalBackdrop: 'rgba(7,17,34,0.44)',
    tabGlass: 'rgba(255,255,255,0.9)',
    tabGlassBorder: 'rgba(221,228,240,0.95)',
    tabGlassHighlight: 'rgba(255,255,255,0.72)',
    tabGlassActive: 'rgba(0,122,251,0.08)',
    subduedButton: '#F4F7FB',
    elevatedSurface: '#F8FBFF',
    overlay: 'rgba(0,0,0,0.45)',
    imageOverlay: 'rgba(0,0,0,0.96)',
    white: '#FFFFFF',
  },
  dark: {
    text: '#E9EDF0',
    background: '#17212B',
    tint: tintColorDark,
    icon: '#9FB0C0',
    tabIconDefault: '#9FB0C0',
    tabIconSelected: tintColorDark,
    screen: '#17212B',
    card: '#1E2C39',
    panel: '#1E2C39',
    border: '#2A3B4C',
    muted: '#93A4B5',
    primary: '#4A8CFF',
    soft: '#22303D',
    surfaceMuted: '#1A2733',
    inputBackground: '#1B2835',
    tabBar: '#17212B',
    tabInactive: '#8091A3',
    badgeBackground: '#22303D',
    separator: '#22303D',
    feedBackground: '#17212B',
    incomingBubble: '#1E2C39',
    incomingText: '#E9EDF0',
    outgoingBubble: '#2D8CFF',
    outgoingText: '#FFFFFF',
    danger: '#F87171',
    success: '#34D399',
    infoSurface: '#10203A',
    infoBorder: '#1D3A63',
    warningSurface: '#2B1A0B',
    warningBorder: '#7C4A16',
    warningText: '#FDBA74',
    dangerSurface: '#33181C',
    dangerBorder: '#7A2630',
    successSurface: '#10261F',
    successBorder: '#1E5C46',
    modalBackdrop: 'rgba(9,14,20,0.78)',
    tabGlass: 'rgba(23,33,43,0.92)',
    tabGlassBorder: 'rgba(60,78,96,0.9)',
    tabGlassHighlight: 'rgba(159,176,192,0.16)',
    tabGlassActive: 'rgba(74,140,255,0.18)',
    subduedButton: '#22303D',
    elevatedSurface: '#1B2835',
    overlay: 'rgba(0,0,0,0.62)',
    imageOverlay: 'rgba(2,6,23,0.97)',
    white: '#FFFFFF',
  },
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
